for check
AndriiMan/Numbers_Task_2 pull request #1
Opened 2021-06-16 13:19 UTC by AndriiMan

for check

2021-06-18 07:11 UTC, AnnaDremluga requested changes

2021-06-18 07:11 UTC, AnnaDremluga commented on src/com/company/Main.java
>          System.out.println(isUglyNum(number) == 1 ? "It is an ugly number." : "It is not an ugly number.");
What java type do we use if we need only 2 states: yes or no?

2021-06-18 07:11 UTC, AnnaDremluga commented on src/com/company/Main.java
> -        //System.out.println(isUglyNum(number));
I would not recommend recursion usage. 
Please, find and tell me deffirince between recursion and loops and why it's better to use loops?

2021-06-18 07:38 UTC, AndriiMan commented on src/com/company/Main.java
>          System.out.println(isUglyNum(number) == 1 ? "It is an ugly number." : "It is not an ugly number.");
Boolean

2021-06-18 07:49 UTC, AndriiMan commented on src/com/company/Main.java
> -        //System.out.println(isUglyNum(number));
Рекурсію ми використовуємо коли функція викликає саму себе, а от цикли ми використовуємо для того, щоб виконувати набір операторів кілька разів. В циклі використання памяті менше.

Recursion is applied to functions, where the function calls itself to repeat the lines of code or certain statements.
Loops, uses looping in order to execute a set of statements multiple times.

2021-06-22 07:54 UTC, AnnaDremluga requested changes

2021-06-22 07:54 UTC, AnnaDremluga commented on src/com/company/Main.java
> +    public static String isUglyNum(int number) {
A method must do only 1 thing whether it's ugly number search or result string definition. Don't mix them 2 together

2021-06-25 09:13 UTC, AnnaDremluga approved these changes

2021-06-25 11:18 UTC, merged